title: The vnetman blog
description: Of routers and switches, datagrams and streams, sharks and Pythons

baseurl: ""
url: "https://vnetman.github.io"

google_analytics:
# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

plugins:
  - jekyll-feed

theme: # leave it empty
